### ISSUE TITLE
[Request] Demoman shield 

### ISSUE THREAD

**Issue by Fate970730** [Batfoxkid/Freak-Fortress-2-Rewrite#71] opened 2023-07-31 13:52 UTC
## Description
maybe it would be possible to make the demoman's shield block a blow like the razorback.  or how is it possible to do it myself?

**Comment by Batfoxkid** [comment] 2023-07-31 18:28
Duplicate of #72

**Closed** 2023-07-31 18:28 UTC
Labels: duplicate, enhancement

**Comment by Fate970730** [comment] 2023-08-01 13:36
I understand, but many people on the server want the demo shield
